"""
N-gram language model scorer for cryptanalysis fitness evaluation.

A candidate plaintext is "fit" when its character sequences match the
statistical patterns of a natural language.  This module quantifies that
fit as a sum of log-probabilities over every overlapping n-gram window in
the candidate text.  The higher (less negative) the score, the more the
candidate resembles the target language.

N-gram file format (one entry per line):
    <NGRAM> <integer-count>

    Example (quadgram file):
        TION 24135
        ATIO 21413
        ...

    The file is assumed to contain only uppercase ASCII letters A-Z.  All
    n-grams must have the same length (length is inferred from the first
    line).  Files may be generated by generate_ngrams.py or downloaded from
    public cryptanalysis resources.
"""

import math
from pathlib import Path


class NGramScore:
    """Evaluate candidate plaintexts against a pre-built language n-gram model.

    The score for a string ``t`` of length ``n`` is::

        score(t) = sum_{i=0}^{n-L} log10( P(t[i : i+L]) )

    where L is the n-gram length and P(gram) is the corpus probability of
    that gram (count / total).  Grams absent from the corpus receive a small
    floor probability (pseudo-count of 0.01) so the score remains finite.

    Usage::

        fitness = NGramScore("path/to/quadgrams.txt")
        score = fitness.score("HELLOWORLD")  # Higher is better
    """

    def __init__(self, ngram_file: str | Path) -> None:
        """Load and preprocess the n-gram frequency file.

        All raw counts are converted to log10 probabilities in place so that
        scoring is a single hash-lookup-and-add inner loop with no division.

        Args:
            ngram_file: Path to the n-gram frequency file.

        Raises:
            FileNotFoundError: If the file does not exist.
            ValueError:        If the file is empty or malformed.
        """
        path = Path(ngram_file)
        if not path.exists():
            raise FileNotFoundError(f"N-gram file not found: {path}")

        self._grams: dict[str, float] = {}
        ngram_length: int | None = None
        total_count: int = 0

        with path.open(encoding="utf-8") as fh:
            for raw_line in fh:
                line = raw_line.strip()
                if not line:
                    continue
                gram, count_str = line.split()
                count = int(count_str)
                self._grams[gram] = count           # Store raw count temporarily
                total_count += count
                if ngram_length is None:
                    ngram_length = len(gram)        # Infer length from first entry

        if ngram_length is None or total_count == 0:
            raise ValueError(f"N-gram file is empty or malformed: {path}")

        self.L: int = ngram_length

        # Convert raw counts to log10 probabilities (in place, no extra dict).
        # Floor probability for unseen grams: pseudo-count 0.01 / total_count.
        self._floor: float = math.log10(0.01 / total_count)
        for gram in self._grams:
            self._grams[gram] = math.log10(self._grams[gram] / total_count)

    def score(self, text: str) -> float:
        """Return the total log10 probability score for a candidate string.

        Slides a window of width ``self.L`` across ``text`` and sums the
        log10 probabilities.  Unknown grams receive the floor value.

        Args:
            text: Uppercase string of A-Z characters to evaluate.
                  Spaces and other non-letter characters should be removed
                  by the caller before scoring so that word-boundary windows
                  do not accumulate floor penalties.

        Returns:
            Summed log10 probability.  Higher (less negative) means a better
            fit to the language model.
        """
        get   = self._grams.get    # Cache attribute lookup for the hot inner loop
        floor = self._floor
        L     = self.L
        total = 0.0

        for i in range(len(text) - L + 1):
            total += get(text[i : i + L], floor)

        return total
